name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - 'v*'

jobs:
  build-documents:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        document: 
          - cheatsheet
          - document
          - exam
          - exercise
          - letter
          - poster
          - presentation
          - report
          - thesis

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: recursive 

      - name: Compile ${{ matrix.document }}
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ${{ matrix.document }}.tex
          compiler: latexmk
          args: "-halt-on-error"

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.document }}-pdf
          path: build/${{ matrix.document }}.pdf